- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: install git software
      apt:
        name: git
        state: present
      when: ansible_facts['os_family'] == "Debain"
    - name: install git software on Redhat
      yum:
        name: git
        state: absent
      when: ansible_facts['os_family'] == "Redhat"  

