--- # my loop playbook for creating users
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
          - name: add list of users in my nodes
            user: name='{{item}}' state=present
            with_items:
                    - sachine
                    - shewag
                    - dravid
                    - ganguliy


