- hosts: all
  become: true
  tasks: 
  - name: vars demo
    debug:
      var: name
  - name: Copy index.html
    template:
      src: index.html
      dest: /var/www/html/index.html
  - name: cat file
    shell: cat /var/www/html/index.html
    register: output
  - name: print file content
    debug:
      var: output.stdout
